url: http://www.solarllc.com
baseurl:

# Site settings
title: Solar Surveying, LLC
email: fsosa@solarllc.com
description: "Solar Surveying - TBPLS Certified"

# Heading
lead-in: "Texas Professional Land Surveyors"
heading: Solar Surveying, LLC

# About
firm: "TBPLS Firm #10194442"

# Team names, titles and social links
people:
- name: Jesus "Fidel" Sosa, RPLS
  pic: placeholder-person.png
  position: President
  license-no: "TBPLS License #6095"

# Postal address (add as many lines as necessary)
address: 5421 Brystone Drive, Houston, TX, 77041

# Build settings
markdown: kramdown
permalink: pretty
